// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/jamesjoshuahill/language/handler"
)

type FakeRecorder struct {
	RecordStub        func(string)
	recordMutex       sync.RWMutex
	recordArgsForCall []struct {
		arg1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRecorder) Record(arg1 string) {
	fake.recordMutex.Lock()
	fake.recordArgsForCall = append(fake.recordArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Record", []interface{}{arg1})
	fake.recordMutex.Unlock()
	if fake.RecordStub != nil {
		fake.RecordStub(arg1)
	}
}

func (fake *FakeRecorder) RecordCallCount() int {
	fake.recordMutex.RLock()
	defer fake.recordMutex.RUnlock()
	return len(fake.recordArgsForCall)
}

func (fake *FakeRecorder) RecordArgsForCall(i int) string {
	fake.recordMutex.RLock()
	defer fake.recordMutex.RUnlock()
	return fake.recordArgsForCall[i].arg1
}

func (fake *FakeRecorder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.recordMutex.RLock()
	defer fake.recordMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRecorder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handler.Recorder = new(FakeRecorder)
